[package]
name = "arena-interface"
authors = ["Gabe Lopez <ismellike@users.noreply.github.com>"]
description = "An interface for interacting with the Arena DAO's protocol."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
doctest = false

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
serde = { workspace = true }
cw-utils = { workspace = true }
dao-interface = { workspace = true }
dao-pre-propose-base = { workspace = true }
dao-voting = { workspace = true }
cw-balance = { workspace = true }
cw-address-like = { workspace = true }
cw-orch = { workspace = true }
cw-ownable = { workspace = true }
cw20 = { workspace = true }
cw721 = { workspace = true }
