[package]
name = "cw-competition-base"
authors = ["Gabe Lopez <ismellike@users.noreply.github.com>"]
description = "A package for creating extendable competitions."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
doctest = false

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
serde = { workspace = true }
cw-utils = { workspace = true }
cw-storage-plus = { workspace = true }
thiserror = { workspace = true }

cw2 = { workspace = true }
cw-balance = { workspace = true }
cw-ownable = { workspace = true }
cw-paginate = { workspace = true }
arena-interface = { workspace = true }

dao-interface = { workspace = true }
dao-pre-propose-base = { workspace = true }
dao-voting = { workspace = true }
