[package]
name = "cw-balance"
authors = ["Gabe Lopez <ismellike@users.noreply.github.com>"]
description = "The Balance package is a Rust library for managing and manipulating balances of native tokens, CW20, and CW721 tokens in a CosmWasm smart contract. This package simplifies handling different token types and provides utility functions for common operations like adding, subtracting, sending, and splitting balances."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
doctest = false

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cw-address-like = { workspace = true }
itertools = { workspace = true }

cw20 = { workspace = true }
cw721 = { workspace = true }
