[package]
name = "scripts"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
cw-orch = { workspace = true }
arena-tournament-module = { workspace = true }
arena-core = { workspace = true }
arena-core-interface = { workspace = true }
arena-escrow = { workspace = true }
cosmwasm-std = { workspace = true }
interface = { workspace = true }
cw-multi-test = { workspace = true }
cw-utils = { workspace = true }
cw-competition = { workspace = true }
cw-balance = { workspace = true }

# scripts specific
dotenv = { version = "0.15.0" }
pretty_env_logger = { version = "0.5.0" }

# cw-orch enabled DAO DAO deps
dao-interface-master = { package = "dao-interface", git = "https://github.com/DA0-DA0/dao-contracts", branch = "main" }
dao-interface = { git = "https://github.com/Kayanski/dao-contracts", branch = "development" }
dao-cw-orch = { git = "https://github.com/Kayanski/dao-contracts", branch = "development" }
dao-proposal-sudo = { git = "https://github.com/Kayanski/dao-contracts", branch = "development" }
dao-proposal-single = { git = "https://github.com/Kayanski/dao-contracts", branch = "development" }
dao-voting = { git = "https://github.com/Kayanski/dao-contracts", branch = "development" }